project:
  type: book
  pre-render: ./scripts/pre_load_penguins.R
  # post-render: ./scripts/post_render_penguins.R

book:
  title: "Pages from Data Frame"
  author: "Nathan Craig"
  date: "11/26/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



